yuvrajsinghgmx/ShopSmart

app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/HomeScreen.kt
gradle/libs.versions.toml

This pull request implements a price estimation feature for the shopping list. Key changes include:
Added input fields for item prices.
Display of total estimated cost as items are added/removed.
Updated data model to include price information.
Ensured real-time total calculation for budget tracking.

Price estimation feature

---

.idea/deploymentTargetSelector.xml
.idea/gradle.xml
.idea/inspectionProfiles/Project_Default.xml
.idea/misc.xml
app/build.gradle.kts
app/src/main/java/com/yuvrajsinghgmx/shopsmart/MainActivity.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/datastore/instance.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/datastore/products.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/HomeScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/viewmodel/ShoppingListViewModel.kt

fixed Items Added to the Shopping List Disappear on App Closure
Used Datastore
viewmodel

Fixed the issue #14

---

.idea/compiler.xml
.idea/kotlinc.xml
.idea/material_theme_project_new.xml
.idea/misc.xml
app/build.gradle.kts
app/src/main/AndroidManifest.xml
app/src/main/java/com/yuvrajsinghgmx/shopsmart/ApiData/Hit.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/ApiData/Pics.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/MainActivity.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/MyApp.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/Repository/ImageRepo.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/api/API.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/datastore/products.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/di/NetworkModule.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/HomeScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/viewmodel/ShoppingListViewModel.kt
build.gradle.kts
gradle/libs.versions.toml

Added Features
Automatic Image Generation based on the user input
Better and Smooth looking UI
Pixabay API used earlier one was having limited access

Feature Request: AI Image Generation for Products fixed #21

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/HomeScreen.kt

For Issue #30 
In HomeScreen.kt:
Added evenly rounded corners for the checkout container.
Added padding at bottom so that it doesn't coincide with system control buttons. 
Added color to the container to differentiate it from the app background.
All points mentioned in the issue have been addressed.

Update HomeScreen.kt - Added changes for Total Cost container

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/Navigation.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/HomeScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/Profile.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/ShopSmartNavBar.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/Upcoming.kt

Refactored theme to follow Material Design standards by removing explicit colour specifications. Also cleaned up some unnecessary imports. @yuvrajsinghgmx please add "hacktoberfest-accepted" label to this PR.

Provided Light Theme / Dark Theme using Material theme

---

.github/workflows/greetings.yml

closes #48 
This is a PR raised for the level1 enhacement of the repository where the Github Actions bot that send a message for the new users who raise a new PR or an issue in the project.
Please add level1 and gssoc-ext labels to this PR.
Thank you.

#Add Github Greetings bot

---

.idea/gradle.xml
.idea/inspectionProfiles/Project_Default.xml
app/build.gradle.kts
app/src/main/AndroidManifest.xml
app/src/main/java/com/yuvrajsinghgmx/shopsmart/MainActivity.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/Navigation.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/profilefeatures/ImageComponents.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/HomeScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/MyOrders.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/Profile.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/ShopSmartNavBar.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/utils/ImageHelper.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/utils/SharedPrefsHelper.kt
app/src/main/res/xml/file_paths.xml
gradle/libs.versions.toml

@yuvrajsinghgmx 
-I have performed everything that the issue says:
1)Added provision of updating and adding photo
2)Added email and name checks for invalid entries
3)My Orders section that dynamically stores checked out items on both Home Screen and the Profile Screen
4)Added a clear button that clears all orders
https://github.com/user-attachments/assets/32cb7e3d-606e-4387-b6bc-45955255ec6b

#41 Profile enhancement and My Orders Section addition 

---

.idea/gradle.xml
.idea/inspectionProfiles/Project_Default.xml
app/build.gradle.kts
app/src/main/AndroidManifest.xml
app/src/main/java/com/yuvrajsinghgmx/shopsmart/MainActivity.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/Navigation.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/profilefeatures/ImageComponents.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/HomeScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/MyOrders.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/Profile.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/ShopSmartNavBar.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/utils/ImageHelper.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/utils/SharedPrefsHelper.kt
app/src/main/res/xml/file_paths.xml
gradle/libs.versions.toml

Reverts yuvrajsinghgmx/ShopSmart#56

Revert "Revert "#41 Profile enhancement and My Orders Section addition ""

---

Readme.md

Addition of All Contributors | Issue #36

---

.idea/deploymentTargetSelector.xml
.idea/gradle.xml
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/HomeScreen.kt

Fixed issue #43 
The check box of the next item does not get auto-checked after we delete an item above it.

Fixed Autocheck check box after item deletion

---

app/build.gradle.kts
app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/Navigation.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/HelpS.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/Profile.kt
app/src/main/res/drawable/gmail.xml
app/src/main/res/drawable/instagram.xml
app/src/main/res/drawable/linkedin.xml
gradle/libs.versions.toml

I have revamped the Help & Support screen to include a comprehensive FAQ section and a "Contact Us" section. The "Contact Us" section features LinkedIn and Instagram links with their respective logos. Additionally, I've changed the minimum SDK and AGP version to be compatible with my system.
Please note: The email I provided is a placeholder as I do not know the correct email address. Kindly update it to the appropriate one.
Thank you for your support!

Enhanced Help & Support Screen with FAQ and Contact Us Sections

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/HomeScreen.kt

A better looking UI with two column lazy grid. #62 
> @yuvrajsinghgmx Please add labels to the PR and tell me if in case you want changes.

Changed from list view to Grid view.

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/HomeScreen.kt

Reverts yuvrajsinghgmx/ShopSmart#71

Revert "Changed from list view to Grid view."

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/datastore/products.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/HomeScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/Upcoming.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/viewmodel/ShoppingListViewModel.kt

User adds a list for a date in future.
That particular list automatically shows up on the Home Screen on D-Date.
List is deleted only after user deletes it manually from the home screen.
solves issue #34 
hey @yuvrajsinghgmx This was lot harder than i expected  :)) So, Please review and Let me know if you require any changes.

Feature: UpComing Page #34

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/datastore/products.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/HomeScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/Upcoming.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/viewmodel/ShoppingListViewModel.kt

Reverts yuvrajsinghgmx/ShopSmart#75
You had used code from ChatGPT which is fine but you should atleast debug the code and check if its working.

Removing PR

---

.idea/deploymentTargetSelector.xml
app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/Navigation.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/HomeScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/MyOrders.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/utils/SharedPrefsHelper.kt

Added a "Select All" checkbox at the top of the item list.
When the "Select All" checkbox is selected, all items will be automatically  selected for deletion.

Feature Added "Select All" Button for Bulk Deletion of Items #72

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/HomeScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/viewmodel/ShoppingListViewModel.kt

(It sorts the list according to your search keyword for you)
@yuvrajsinghgmx Please add hacktoberfest and gssoc labels. Also i thought sorting wouldn't make sense as the list is already sorted as per date so i skip the sorting feature.

added search Bar

---

.idea/.name
.idea/compiler.xml
.idea/gradle.xml
.idea/misc.xml
app/src/main/java/com/yuvrajsinghgmx/shopsmart/MainActivity.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/Navigation.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/Cart.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/HomeScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/ShopSmartNavBar.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/viewmodel/ShoppingListViewModel.kt

closes issue no. #68 
This PR improves the cart screen by adding a checkout button and displaying the total cost at the top. Users can now remove items from the cart
https://github.com/user-attachments/assets/00dd55b1-f6aa-4cf2-a06e-e740b29a2410
. These enhancements aim to streamline the shopping experience and provide essential information clearly.

Enhance Cart UI with Checkout Functionality and Total Cost Display

---

.idea/runConfigurations.xml
app/build.gradle.kts
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/Signup.kt
gradle/libs.versions.toml

i have improved the UI of the Signup screen.
Here is the improved version UI:-
@yuvrajsinghgmx please  verify the changes and merge the code.

Improved the UI of the signup screen.

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/Navigation.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/EmailSignUpScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/Signup.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/TermsCondition.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/ui/theme/Color.kt
app/src/main/res/values/strings.xml

I have created the UI of the TermsCondition screen #113 
Here is the UI:-
https://github.com/user-attachments/assets/5e897ae4-2711-4752-aebf-e7a19a7c8d76
@yuvrajsinghgmx  please review my code and accept my pull request

UI of the TermsCondition screen

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/datastore/products.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/Navigation.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/EmailSignUpScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/HomeScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/ListScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/MyOrders.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/Profile.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/ShopSmartNavBar.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/Signup.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/TermsCondition.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/viewmodel/ShoppingListViewModel.kt

- Added favorites screen along with favorite button on shopping #61 
- Fixed issue - two data classes for Product instead of one

Added favorites screen #61

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/datastore/products.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/Navigation.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/EmailSignUpScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/HomeScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/ListScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/MyOrders.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/Profile.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/ShopSmartNavBar.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/Signup.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/TermsCondition.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/viewmodel/ShoppingListViewModel.kt

Reverts yuvrajsinghgmx/ShopSmart#123

Revert "Added favorites screen #61"

---

Readme.md
contributors.md

done with issue no #76 
hey @yuvrajsinghgmx
First things First , I am really sorry for the delay , i was caught up in some work 
I have added the documentation , please check it and tell me if any changes are required 
Thankyou

added contributors.md

---

CODE_OF_CONDUCT.md

I created code of conduct file with all necessary things.

Added Code of conduct file

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/Repository/ImageRepo.kt

Added all the changes as mentioned.
@yuvrajsinghgmx

Modified ImageRepo.kt

---

contributors.md

I have enhanced the document and also added some new sections
Done the following changes :-
1) Enhanced the project structure
2) Added star our repository section
3) Enhanced the help and support section by adding email and fixing its alignment
4) Added need help with the basics section
5) Add first pull request steps section
6) Add additional method of contributing through GitHub desktop section
7) Add good coding practices section
8) Add the help and support section
9) Add the pull request rules section
10) Add issue report process section
Fixes:[#132 ]
Closes:[#132 ]

Done the enhancements and also added some new sections

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/HomeScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/Signup.kt

@yuvrajsinghgmx I have successfully added the exit alerts pop up for HomeScreen as well as Signup Activity Page
https://github.com/user-attachments/assets/2b035f8a-f274-4447-a82d-77ffc7319078

#140 Added Exit Alert Pop Ups for HomeScreen and Signup Activities

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/datastore/products.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/ListScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/MyOrders.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/utils/SharedPrefsHelper.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/viewmodel/ShoppingListViewModel.kt

Fixed Error- poduct in data class and also double definition of product class ( in data class and list screen) #134

Fixed Error: Poduct to Product #134

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/ShopSmartNavBar.kt

#96 fixed backstack issue of this app now if you click back when on any screen it moves you to homescreen and when you press back on home screen it gives you option to exit the app;

Backstack fixed #96

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/Navigation.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/profilefeatures/UserDataStore.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/AddressBook.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/PaymentMethods.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/PersonalInformation.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/Security.kt

Issue #152
@yuvrajsinghgmx I have successfully added the Account Settings. The working video is attached below:
https://github.com/user-attachments/assets/9f300131-ef0f-4e80-a817-47c48fc867a8

#152 Added the Account Settings

---

app/src/androidTest/java/com/yuvrajsinghgmx/shopsmart/ExampleInstrumentedTest.kt

#144 
Fix Minor issues Such as Naming Conventions, Hardcoded Strings etc 
Done with all the changes.
@Muhasif-Hafiz

Strengthened File

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/Navigation.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/Contact.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/FAQ.kt

Issue #169
@yuvrajsinghgmx I have added the said components . Please see the attached video:
https://github.com/user-attachments/assets/b0071a91-fddf-44ee-a93b-2cc624913e86

#169 Added the Working of Icons and FAQ Screen in Contact Settings

---

.idea/gradle.xml
app/build.gradle.kts
app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/Navigation.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/ShopSmartNavBar.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/Theme.kt

#168 fixed this issue of recomposition of the screen when clicking on the same option in the navigation bar
also fixed some minor errors that are present in code

#168 fixed screen recomposition issue and also fixed some errors 

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/Navigation.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/BrandFavorites.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/Recommendations.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/SearchHistory.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/SizePreferences.kt
app/src/main/res/drawable/brand_electronics_24px.xml
app/src/main/res/drawable/brand_fashion_24px.xml
app/src/main/res/drawable/brand_home_24px.xml
app/src/main/res/drawable/brand_sports_24px.xml
app/src/main/res/drawable/category_24px.xml
app/src/main/res/drawable/checkroom_24px.xml
app/src/main/res/drawable/clear_24px.xml
app/src/main/res/drawable/close_24px.xml
app/src/main/res/drawable/clothing_24px.xml
app/src/main/res/drawable/delete_24px.xml
app/src/main/res/drawable/delete_sweep_24px.xml
app/src/main/res/drawable/devices_24px.xml
app/src/main/res/drawable/favorite_border_24px.xml
app/src/main/res/drawable/favorite_filled_24px.xml
app/src/main/res/drawable/fitness_center_24px.xml
app/src/main/res/drawable/search_24px.xml
app/src/main/res/drawable/shoes_24px.xml
app/src/main/res/drawable/waist_24px.xml

Issue #177
@yuvrajsinghgmx I have added the mentioned components . Also , can you please be available from tomorrow till 31st October , 7 p.m as I will raise new issues and I just want to gain some additional points on the leaderboard before the event ends....
Anyways , here is the attached video for your reference . Thanks :)
https://github.com/user-attachments/assets/16df0f1b-8bef-4607-940f-1a66d1d58653

#177 Added the Implementation for Personalization Settings

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/Navigation.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/ChatSupport.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/Feedback.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/ReportAnIssue.kt

Issue #181
@yuvrajsinghgmx I have added the mentioned components . Kindly check the video for reference . Cheers :)
https://github.com/user-attachments/assets/88823201-a582-44bf-8ddb-3c6ededaac0b

#181 Added the Implementation for Support and Help Settings

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/Navigation.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/BillingHistory.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/DigitalWallet.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/RefundSettings.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/SavedCards.kt
app/src/main/res/drawable/account_balance_24px.xml
app/src/main/res/drawable/add_24px.xml
app/src/main/res/drawable/add_card_24px.xml
app/src/main/res/drawable/arrow_downward_24px.xml
app/src/main/res/drawable/arrow_forward_24px.xml
app/src/main/res/drawable/arrow_upward_24px.xml
app/src/main/res/drawable/check_circle_24px.xml
app/src/main/res/drawable/download_24px.xml
app/src/main/res/drawable/edit_24px.xml
app/src/main/res/drawable/filter_list_24px.xml
app/src/main/res/drawable/payment_24px.xml
app/src/main/res/drawable/receipt_long_24px.xml
app/src/main/res/drawable/refresh_24px.xml
app/src/main/res/drawable/send_24px.xml
app/src/main/res/drawable/visa_24px.xml

Issue #183
@yuvrajsinghgmx  I have added every component that I mentioned. Kindly check the attached video .... Cheers :)
https://github.com/user-attachments/assets/8e7957c6-7857-46b4-a714-f482d71d7b90

#183 Added the Implementation for Payment and Billing Settings

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/Navigation.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/MissingRefund.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/ReturnGuidelines.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/TrackRefundStatus.kt
app/src/main/res/drawable/block_24px.xml
app/src/main/res/drawable/expand_less_24px.xml
app/src/main/res/drawable/expand_more_24px.xml
app/src/main/res/drawable/inventory_24px.xml
app/src/main/res/drawable/schedule_24px.xml
app/src/main/res/drawable/tips_and_updates_24px.xml

Issue #191
@yuvrajsinghgmx I have added the said features . Kindly view the attached video . Thanks :)
https://github.com/user-attachments/assets/928ad0df-5220-4c64-b48d-d6f46c38ff65

#191 Added the Common Issues Section in Refund Settings -> Contact Support

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/Navigation.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/profilefeatures/TransactionModels.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/DigitalWallet.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/PaymentHistory.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/PaymentMethods.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/SpendingAnalytics.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/ViewStatements.kt
app/src/main/res/drawable/arrow_back_24px.xml
app/src/main/res/drawable/calendar_month_24px.xml
app/src/main/res/drawable/lightbulb_24px.xml
app/src/main/res/drawable/trending_down_24px.xml
app/src/main/res/drawable/trending_up_24px.xml

Issue #195
@yuvrajsinghgmx I have added the said components , Kindly, see the attached video for your reference ... Cheers :)
https://github.com/user-attachments/assets/10092806-72fd-422d-9e89-b80ec3c77311

#195 Implemented Top features of Payment Methods

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/Navigation.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/ProductDetail.kt
app/src/main/res/drawable/shopping_cart_24px.xml
app/src/main/res/drawable/star_rate_24px.xml
app/src/main/res/drawable/swap_horiz_24px.xml

Issue #203
1)Fixed the Navigation Bug and Scrollable Bug.
2)Along with that , I did some cosmetic changes to match the app's UI Structure .
@yuvrajsinghgmx Kindly , see the referenced video for output results .... Can you put level-3 tags if you don't mind....Thanks :)
https://github.com/user-attachments/assets/9853004b-ba54-472a-bb4e-8f31143eaeea

#203 Fixed the navigation and Scrollable Bug

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/Navigation.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/profilefeatures/BankAccountManager.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/AddBankAccountScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/BankAccountDetailsScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/PaymentMethods.kt

Issue #202
@yuvrajsinghgmx Implemented the Bank Account Section Completely , Kindly see the referenced video ... Thanks :)
https://github.com/user-attachments/assets/8587bb4a-985b-47b5-9ec3-168b1b343853

#202 Implemented Bank Accounts Section Completely

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/Navigation.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/ListScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/MyOrders.kt

@yuvrajsinghgmx I have done the following:
1)Dynamic Addition and Removal of items , dynamic addition and subtraction of prices
2)Even Updates at Checkout time
3)Updated the MyOrders.kt as well for dynamically updating price information as the number of products increase and decrease accordingly
Kindly , see the referred output video . Thanks :)
Can you add level-3 labels , this issue was a bit time consuming as well...
https://github.com/user-attachments/assets/f25b667a-7713-47c0-9dfa-4b77498946c6

#213 Implemented the logic for Adding and Checking Out Dynamically

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/Navigation.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/AutoPayScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/PaymentLimits.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/PaymentMethods.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/PaymentSecurity.kt
app/src/main/res/drawable/password_24px.xml

Issue #217
I have added the following:
1)Payment Security
2)Auto-Pay
3)Payment Limits
@yuvrajsinghgmx Kindly, see the referenced video . Thanks :)
https://github.com/user-attachments/assets/a2aafa54-6121-40c6-88f1-2cdb24e579a3

#217 Added the Payment Settings Option

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/Navigation.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/payments/AutoPayScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/payments/PaymentLimits.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/payments/PaymentMethods.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/payments/PaymentSecurity.kt
app/src/main/res/drawable/password_24px.xml

PR #225
@yuvrajsinghgmx I have updated the Contents . The issue was with the migration of packages (organizing into sections) . I have resolved this issue now . You can merge the PR...Thanks :)

Updated the Reverted PR

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/Navigation.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/home/FavoriteScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/home/HomeScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/orders/ProductDetail.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/viewmodel/HomeScreenViewModel.kt

#61 Favorite screen UI added for backend i need data of product like rating, price and platform where it is listed so I only created the UI of this page.

#61 favorite screen UI added

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/home/ListScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/profile/Profile.kt

#212 
improved UI of topAppBar
name of app is removed from it
changes icons and their looks
also added animation in search bar

#212 improve UI of topAppBar of ListScreen

---

.idea/deploymentTargetSelector.xml
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/profile/Profile.kt

fixed this issue now it opens my Order Screen

#232 fixed my Orders Crashing Issue

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/support/CallSupport.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/support/ChatSupport.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/support/ContactSupport.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/support/EmailSupport.kt

ISSUE #239
@yuvrajsinghgmx Please assign labels to this issue . Here are the changed screens after removing scaffolds and optimizing space (Reduced wastage of top space).

#239 Removed Scaffolds and optimized space

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/preferences/AddressBook.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/settings/PrivacySettings.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/settings/Theme.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/support/FAQ.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/support/LiveChat.kt

Issue #241
@yuvrajsinghgmx I have removed scaffolds for the mentioned files. Kindly , see the attached screenshots for your reference. Thanks:)

#241 Removed Scaffolds and optimized space for the mentioned files

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/preferences/BrandFavorites.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/preferences/Currency.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/preferences/Language.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/preferences/SearchHistory.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/preferences/ShippingPreferences.kt

Issue #244
@yuvrajsinghgmx Kindly, see the referenced screenshots and merge the PR...Thanks :)

#244 Removed Scaffolds and optimized space for the mentioned files-3

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/payments/AddBankAccountScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/payments/AddDigitalWalletScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/policies/PrivacyPolicy.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/policies/Terms.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/preferences/SizePreferences.kt

Issue #246
@yuvrajsinghgmx I have removed scaffolds for the mentioned files and optimized space . Kindly, see the attached screenshots for reference . Thanks :)

#246 Removed Scaffolds and optimized space for the mentioned files -4

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/payments/AddSavedCard.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/payments/AutoPayScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/payments/BankAccountDetailsScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/payments/BillingHistory.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/payments/DigitalWallet.kt

Issue #248
@yuvrajsinghgmx I have successfully removed scaffolds and optimized space for the mentioned files . Below are the screenshots for your reference...Kindly, merge the PR.. Thanks :)

#248 Removed Scaffolds and optimized space for the mentioned files -5

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/orders/ApplePaySetupScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/orders/MissingRefund.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/payments/SavedCards.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/payments/Security.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/payments/ViewStatements.kt

Issue #252
@yuvrajsinghgmx I have removed scaffolds and optimized space . Kindly , refer the below screenshots ....Thanks :)

#252 Removed Scaffolds and optimized space for the mentioned files -7

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/orders/MyOrders.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/orders/OrderNotifications.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/orders/RefundHistory.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/orders/RefundPolicy.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/orders/RefundSettings.kt

Issue #254
@yuvrajsinghgmx I have removed Scaffolds and optimized space for the mentioned files.. Kindly merge the PR...Thanks :)

#254 Removed Scaffolds and optimized space for the mentioned files -8

---

app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/appinfo/AppVersion.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/home/ListScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/orders/ReturnGuidelines.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/orders/TrackRefundStatus.kt

Issue #256
@yuvrajsinghgmx I have removed scaffolds and optimized space for each component , Kindly merge my P.R by 7p.m...Thanks :)

#256 Removed Scaffolds and optimized space for the mentioned files -9

---

app/build.gradle.kts
app/src/main/java/com/yuvrajsinghgmx/shopsmart/datastore/products.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/home/ListScreen.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/profile/Profile.kt
app/src/main/java/com/yuvrajsinghgmx/shopsmart/viewmodel/ShoppingListViewModel.kt
gradle/libs.versions.toml

I have added the swiping functionality for deleting each shopping list item from the list. I am adding a video here.
We transfer Link: [https://we.tl/t-diz7rVoI7x](url)
The above link will contain the video of the implemented functionality.

Shopping list item to be deleted when swiped from start to end.

---

README.md
package-lock.json

hi @yuvrajsinghgmx 
This PR focuses on improving the README.md file to make the documentation clearer, more visually appealing, and easier for contributors and users to navigate.
✅ Changes Made:
✨ Improved formatting and readability
🔍 Structured feature descriptions with proper headings and bullet points
🧱 Polished the tech stack and setup instructions
🧑‍💻 Highlighted contributor roles and project links
📌 Added emojis and badges for better presentation
📝 Fixed minor grammatical and spacing issues
⚠️ Note:
This PR does not include any code changes — it is limited to documentation only.
Screenshots are left as (Coming Soon) since I don’t have access to actual app visuals.
🙋🏻‍♀️ About Me:
I’m Sree Chandana, contributing as part of GSSoC’25.
This is one of my initial contributions, and I’m …

Update readme 269

---

android-new/.idea/misc.xml
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/modelclass/SearchResult.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/modelclass/Shop.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/modelclass/repository/Repository.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/NavBar.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/SearchScreen.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/home/HomeState.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/home/HomeViewModel.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/home/components/MiniProductCard.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/sharedComponents/SearchBar.kt
android-new/gradle/libs.versions.toml

Succesfully implemented the Search Screen. I even updated the HomeVIewMode.kt for effective search function. I had to update or add new products and shops for variety , along with similar products being in the same shop for showcasing the lazy row working and lazy coloumn working as a whole. Also ensured dark mode configuration are proper. I made a new data class for SearchResults for the implementation. Kindly check. Also necessary comments were added.

Search Screen Implemented

---

android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/NavBar.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/LoginScreen.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/userprofilescreen/UserProfileScreen.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/userprofilescreen/viewmodeluser/AuthViewModel.kt

As per the request I have limited the phone number length to 10 and otp to 6

Limited the length of phone number and otp

---

backend-new/id_token generator.html

Run this html file using any live server extension.
Use default phone number and otp (i.e., phone number: +919999999999, otp: 000000).

html file to generate id_token

---

android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/NavBar.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/home/HomeScreen.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/home/SharedProductViewModel.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/home/components/ProductCard.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/productDetailsScreen/ProductDetails.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/productDetailsScreen/ProductDetailsUI.kt

#400
added navigation logic from HomeScreen -> ProductDetailsScreen
on tapping Product card user is navigated to the details page

Implement navigation from HomeScreen to ProductDetailsScreen on Product card tap

---

android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/home/HomeScreen.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/shops/AddShop.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/shops/ShopFormState.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/shops/ShopViewModel.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/sharedComponents/MapSection.kt

Fixes #407 
Enhanced Add shop screen UI / Dark mode support / Button loader added

Added shops screen UI enhancement

---

android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/data/modelClasses/Review.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/data/modelClasses/ReviewModels.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/data/modelClasses/Shop.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/data/repository/Repository.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/navigation/NavBar.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/home/ShopDetail.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/productDetailsScreen/ProductDetails.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/productDetailsScreen/ProductDetailsUI.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/productDetailsScreen/components/StarRating.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/review/ReviewScreen.kt

ProductDetailsScreen -> navigates to ReviewScreen when user clicks on ratings
ShopDetailsScreen -> navigates to ReviewScreen when user clicks on ratings

Implement Navigation from ProductDetailsScreen and ShopDetailsScreen to ReviewScreen

---

android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/onboarding/OnboardingScreen.kt

Fixes #437 
https://github.com/user-attachments/assets/f29f4ede-8f44-4c13-a1cb-274b7e37e442

Onboarding role selection navigation issue solved.

---

admin/shopsmart-admin/src/components/DashboardCard.jsx
admin/shopsmart-admin/src/components/Modal.jsx
admin/shopsmart-admin/src/components/Sidebar.jsx
admin/shopsmart-admin/src/hooks/useProducts.js
admin/shopsmart-admin/src/hooks/useShops.js
admin/shopsmart-admin/src/pages/ComingSoon.jsx
admin/shopsmart-admin/src/pages/Dashboard.jsx
admin/shopsmart-admin/src/pages/Login.jsx
admin/shopsmart-admin/src/pages/ManageProducts.jsx
admin/shopsmart-admin/src/pages/ManageShops.jsx
admin/shopsmart-admin/src/services/api.js

Clicking on `shop`'s name or `product`'s name in `manage shops` or `manage product` page opens a modal which shows complete details about the object.

modal view for shop & product details in admin panel

---

admin/shopsmart-admin/src/pages/ManageShops.jsx
backend-new/ShopSmart/mainapp/serializers.py

added: document images in shop modal

---

android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/data/interfaces/FavoritesApi.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/data/repository/FavoritesRepository.kt
android-new/app/src/main/java/com/yuvrajsinghgmx/shopsmart/screens/productDetailsScreen/SharedProductViewModel.kt

FIX: resolve issue where product saved toggle was not working
